### ISSUE TITLE
Regular docker container

### ISSUE THREAD

**Issue by GloryOfUkraine** [disbalancer-project/main#13]
Please create regular docker container which could be installed using command `docker pull disbalancer/project-main` command.
That would be much more ease to deploy to VPS using bunch of commands such as pull and start. Instead of installing zip app, installing compiler, unpack sources, compile and run. So complicated

**Comment by Gorlanson** [comment]
Got it, will do
Thank you for your feedback

**Comment by Gorlanson** [comment]
Try this one:

1) docker pull disbalancer/disbalancer:manifest-latest
2) docker run disbalancer/disbalancer:manifest-latest

**Comment by trinitiwowka** [comment]
Проблема все равно сохраняется, спустя какое-то время, падает версия вижу тут еще старая https://hub.docker.com/r/disbalancer/liberator/tags

**Comment by Gorlanson** [comment]
> Проблема все равно сохраняется, спустя какое-то время, падает версия вижу тут еще старая https://hub.docker.com/r/disbalancer/liberator/tags



> Проблема все равно сохраняется, спустя какое-то время, падает версия вижу тут еще старая https://hub.docker.com/r/disbalancer/liberator/tags

Были бы признательны если поделитесь логом ошибки.
По поводу докер версии, она с автоапдейтов внутри, поэтому не нужно обновлять докер при новом релизе Liberator-а

**Comment by trinitiwowka** [comment]
из последнего вижу 
2022-04-02T16:07:25Z	Massive https://acron.ru/ attacking...
2022/04/02 16:07:27 updating...
panic: open /root/.disbalancer-go-client/app: text file busy

goroutine 24 [running]:
main.Unexpected(...)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:117
main.MustWrite(0xc0000ba080, 0x20, 0xc001e34000, 0x7ce802, 0x8ac000)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:104 +0x125
main.main.func1(0x12a05f200)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:61 +0x1cc
main.main.func2()
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:67 +0x45
main.main.func3(0xc000010c40, 0xc000152000, 0xc000010c30)
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:80 +0x2b
created by main.main
	/Users/alex/Downloads/go-dev-dbr/disbalancer-go-client/launcher/main.go:79 +0x51a
