### ISSUE TITLE
Multiple errors on launch

### ISSUE THREAD

**Issue by christianYoopies** [disbalancer-project/main#6]
Windows 7 x64, OS X
On launching have these 2 errors:
```
Failed to read file:open proxies.txt: no such file or directory
Failed to get country:open GeoLite2-Country.mmdb: no such file or directory

```
**target to attack seems on OS X to be found immediately so it works while on Windows app stuck trying to find target to attack**

**Comment by christianYoopies** [comment]
@swistjkee

**Comment by SpiritOfWill** [comment]
Hi. This is a minor error and it was fixed in the https://github.com/disbalancer-project/main/releases/tag/0.0.8
